### ISSUE TITLE
[node 0.12] Responses that have ended still trigger _onTimeout

### ISSUE THREAD

**Issue by mridgway** [yahoo/node-limits#10]
We are seeing issues with limits not detaching the timer for `inc_req_timeout`. I think it may due to the [`free` event](https://github.com/yahoo/node-limits/blob/master/lib/index.js#L89) not being called for incoming requests. I couldn't find any information on where this event is supposed to come from (I don't see it in stream or net API).

Should this instead be using the socket `close` event?

**Comment by mridgway** [comment]
On second thought, it doesn't seem like this is the issue. The responses are clearly being `end`ed, but limits is still reporting a timeout.

**Comment by mridgway** [comment]
Adding a simple `if (this.message.finished) { return; }` inside of `_onTimeout` helps, but it seems like there should be a better way to clear that timeout.

**Comment by evantorrie** [comment]
Finally fixed (after an extensive debug session) by #15
